name: Kotlin Backend CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set up application.properties for testing
        run: |
          echo "pusher.app-id=${{ secrets.PUSHER_APP_ID }}" >> src/test/resources/application-test.properties
          echo "pusher.key=${{ secrets.PUSHER_KEY }}" >> src/test/resources/application-test.properties
          echo "pusher.secret=${{ secrets.PUSHER_SECRET }}" >> src/test/resources/application-test.properties
          echo "pusher.cluster=${{ secrets.PUSHER_CLUSTER }}" >> src/test/resources/application-test.properties
          echo "spring.profiles.active=test" >> src/test/resources/application-test.properties

      - name: Print test configuration
        run: cat src/test/resources/application-test.properties

      - name: Build with Gradle
        run: ./gradlew build --info

      - name: Run tests with debug output
        run: ./gradlew test --debug
        env:
          SPRING_PROFILES_ACTIVE: test

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: build/reports/tests/test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build JAR
        run: ./gradlew bootJar

      # Add your deployment steps here
      # For example, you might use SSH to deploy to a server or push to a cloud service
      - name: Deploy to server
        run: |
          echo "Add your deployment commands here"
          # Example: scp ./build/libs/your-app.jar user@your-server:/path/to/deploy